[package]
name = "playwright-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
playwright-rs = { git = "https://github.com/padamson/playwright-rust", branch="main" }

thirtyfour = "0.36.1"
tokio = { version = "1.49.0", features = ["process"] }
